Add feed
YP-Maverick/java-filmorate pull request #15
Opened 2024-05-06 19:17 UTC by JabaHott

Реализован функционал истории действий пользователя

2024-05-06 20:27 UTC, YP-Maverick approved these changes
Все отлично

2024-05-06 20:27 UTC, YP-Maverick approved these changes

2024-05-06 21:22 UTC, PAndrey87 requested changes

2024-05-06 21:22 UTC, PAndrey87 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/EventDbStorage.java
> +        String sqlQuery = "SELECT EVENT_ID, \"TYPE\", OPERATION, EVENT_TIMESTAMP, USER_ID, ENTITY_ID FROM PUBLIC.EVENTS WHERE USER_ID = ?";
Тут ты экранировал TYPE вероятно из-за того что он зарезервированно в SQL. Может заменить его не EVENT_TYPE ?

И есть ли смысл в перечислении всех полей, не проще ли использовать SELECT * FROM PUBLIC.EVENTS WHERE USER_ID = ?

2024-05-06 21:22 UTC, PAndrey87 commented on src/main/java/ru/yandex/practicum/filmorate/service/review/ReviewService.java
> +        eventStorage.add("REVIEW", "ADD", review1.getUserId(), review1.getId());
Поля OPERATION и TYPE содержат повторяющиеся значения может стоит использовать для них ENUM ?

2024-05-07 07:46 UTC, JabaHott commented on src/main/java/ru/yandex/practicum/filmorate/service/review/ReviewService.java
> +        eventStorage.add("REVIEW", "ADD", review1.getUserId(), review1.getId());
Перенес на enum, но я вообще изначально рассматривал вынос в отдельные таблы. Т.к. с увеличением приложения и логики придется делать и запросы и дополнять перечисления (+ идея для рефактора в принципе)

2024-05-07 10:05 UTC, PAndrey87 approved these changes
Все отлично.

2024-05-07 10:31 UTC, merged